### ISSUE TITLE
Please issue an xdis release

### ISSUE THREAD

**Issue by ddash-ct** [rocky/python-xdis#130]
## Description

Request to please issue a release of xdis, particularly since the latest in master can be installed on systems using Python 3.11 and 3.12

## Priority

Believe this is ideal for the community to enable using as a pinned dependency

**Comment by rocky** [comment]
Thanks for the input.  This is something I'm aware of and is a medium-priority project for me. Demonstrations of support (upvoting, further comments, technical support, monetary support) would raise the priority. If people have specific needs (for example, if you're an OS packager and there's a deadline for submitting packages), that would be important for me to know, as well.

**Comment by ddash-ct** [comment]
Sounds good. Just to clarify using, I'm able to use the library on Python 3.11 by installing directly from the git repo using the "xdis @ git+**" syntax, but was curious if there was interest in marking a new release where the
`python_requires` limitation has shifted to include Python 3.12.

**Comment by alamerrouka** [comment]
pydumpck "/sdcard/Download/GAY_TEAM/enc_simple.cpython-311.so"           Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/pydumpck", line 5, in <module>
    from pydumpck import run
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pydumpck/__init__.py", line 22, in <module>
    from pydumpck.pyinstaller_dump import run
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pydumpck/pyinstaller_dump.py", line 4, in <module>
    from pydumpck.py_common_dump import CommonDump
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pydumpck/py_common_dump/__init__.py", line 7, in <module>
    from ..py_package import PackageStruct, PackageDescription
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pydumpck/py_package/__init__.py", line 1, in <module>
    from .package_description import PackageDescription
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pydumpck/py_package/package_description/__init__.py", line 6, in <module>
    from PyInstaller.utils.cliutils.archive_viewer import get_archive, get_data, get_content, get_archive_content
ImportError: cannot import name 'get_archive' from 'PyInstaller.utils.cliutils.archive_viewer' (/data/data/com.termux/files/usr/lib/python3.11/site-packages/PyInstaller/utils/cliutils/archive_viewer.py)

how can i solve this problem

**Comment by rocky** [comment]
I  have just learned that I will be speaking at [BlackHat 2024 Asia, April 16-19](https://www.blackhat.com/asia-24/).  Hope to see you all there.

Therefore there will probably be a release of `xdis` in advance of that.
