### ISSUE TITLE
Stopping at the middle of the decompilation

### ISSUE THREAD

**Issue by lululepu** [rocky/python-xdis#134]
Hey when i do this:
```py
loaded = xdis.load_module_from_file_object(io.BytesIO(v))
insts: list[dis.Instruction] = xdis.Bytecode(loaded[3], xdis.get_opcode(loaded[0], False)).dis(loaded[3])
print(insts)
```
i get the dis of "v" but its not complete like stop at the middle of the decompilation:
```
             860 LOAD_CONST           (None)
             862 RETURN_VALUE
         >>  864 LOAD_CONST           (None)
             866 RETURN_VALUE
         >>  868 LOAD_CONST           (None)
             870 RETURN_VALUE

End here
```

but when i use pydisasm command or dis module i get it completely can i get help?

**Comment by rocky** [comment]
This is vague. It feels like you haven't done your homework before asking help.  Does this occur for all bytecode, or just some particular bytecode?  If particular bytecode what are the characteristics of the bytecode, e.g. which python version and so on.

Aside from being vague the code is a bit complicated too. Can you simplify it by filling in parameter with constant values?  

BTW the type annotation `list[dis.Instruction]` is wrong. A xdis.Instruction is not the same thing as a `dis.Instruction`.

**Comment by lululepu** [comment]
Hey, sorry for the inconvenience. I found a way to "fix" it. I didn't know that this method didn't disassemble all the code (func/class). Thanks for the response, and sorry for the low-quality issue. I don't do this often, and I wrote the code quickly. Thx :D
