### ISSUE TITLE
GitHub releases don’t match PyPI

### ISSUE THREAD

**Issue by alexwlchan** [rocky/python-xdis#15]
The latest version of [xdis on PyPI](https://pypi.org/project/xdis/#description) is 3.2.0.

The latest version in the [list of GitHub releases](https://github.com/rocky/python-xdis/releases) is 3.1.0.

Please add a GitHub release for the PyPI release – the first time I looked, I didn’t realise xdis had been updated recently.

**Comment by rocky** [comment]
Release 3.2.0 is now tagged with commit 0c481b3056bbe2914413db11ca20311027ecf56b

**Comment by alexwlchan** [comment]
Thanks!
