### ISSUE TITLE
Is unmarshal safe?

### ISSUE THREAD

**Issue by android1257** [rocky/python-xdis#151]
### Research questions on serialization security

I'm doing research related to serialization security and learned that the `marshal` provided by Python can lead to the execution of malicious code when deserializing malicious content. Based on this, I have the following questions:

1. **Your Work vs. Downstream Work**  
   Is your work, including decompiling `.pyc` files, able to circumvent the insecurity of `marshal`?  
   - Does your tool run without executing code like `pickletools`, or is it something like `marshal.load` that may result in code execution?

2. **Current '.pyc' decompilation tool**  
   What does the current `.pyc` decompilation tool do when deserializing?

Thank you so much!

**Comment by rocky** [comment]
This is not a forum soliciting survey questions for research or otherwise.
