### ISSUE TITLE
Bug somewhere in deparse_code caused by ea8649d

### ISSUE THREAD

**Issue by alexwlchan** [rocky/python-xdis#16]
One of two bugs found in Hypothesis CI, I’m afraid. This comes from https://github.com/HypothesisWorks/hypothesis-python/issues/382.

We have two tests failing, on PyPy only, that are caused by something in xdis 3.2.0.

<details>
<summary>

Environment config</summary>

``` console
$ pip freeze
cffi==1.3.0
enum34==1.1.6
greenlet==0.4.9
hypothesis==3.5.3
readline==6.2.4.1
spark-parser==1.4.0
uncompyle6==2.9.3
wheel==0.24.0
xdis==3.2.0

$ python --version
Python 2.7.10 (850edf14b2c75573720f59e95767335fb1affe55, Oct 30 2015, 00:18:28)
[PyPy 4.0.0 with GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)]
```

</details>

This snippet reproduces one of the issues:

``` python
from hypothesis import strategies as st
from io import BytesIO
import sys

from uncompyle6 import deparse_code

f = lambda right: [].map(lambda length:())
out = BytesIO()
deparse_code(2.7, f.__code__, out=out, is_pypy=True)
print(out.getvalue())
```

Our test expects this to return

```
return [].map(lambda length: ())
```

but in fact we get

```
return [].None(lambda length: ())
```

Playing around with git bisect, it looks as if this caused by a change in xdis, specifically https://github.com/rocky/python-xdis/commit/ea8649d9b2b168c27f8409508d29cbb90f345e1e. Unfortunately I don’t know enough about Python bytecode parsing to say what in this commit might be causing the issue.

As with the previous issue, we can get around this by pinning versions, but it would be nice if that wasn’t necessary.

This is one of two bugs our CI spotted. I suspect they have the same root cause, as the symptoms are the same; I haven’t had time to get a minimal example for the second failure yet.

**Comment by rocky** [comment]
Ok. I see what's wrong. Just need to write a test for it and I'll be done. 

It would be sufficient just to put out a new release 3.2.1, right?

**Comment by alexwlchan** [comment]
A 3.2.1 release would be fine, thanks.

**Comment by rocky** [comment]
[done](https://pypi.python.org/pypi?name=xdis&version=3.2.1&:action=display) and [tagged in git](https://github.com/rocky/python-xdis/tree/release-3.2.1).

**Comment by alexwlchan** [comment]
Super, thanks! I’ve tested locally; seems to be fixed for me.

I’ll run it on the Hypothesis CI, and assuming that all works, I’ll be able to close this.

**Comment by alexwlchan** [comment]
Yep, this works in our CI. Clean runs again. Hopefully that's it for now.

Thanks for all your help!

**Comment by rocky** [comment]
Sigh. Just discovered a xdis bug in stackless-3.4.2 which seems to use opcode_pypy32.py .  Commit d87f05a addresses this.
