### ISSUE TITLE
xdis-3.3.0 release tarball errors in setup.py

### ISSUE THREAD

**Issue by dol-sen** [rocky/python-xdis#33]
Seems this code was not committed, but was in the release tarball.  Looks like a copy/paste error.
You should likely re-release as 3.3.1 with the fixed code.

/usr/bin/python3.5 setup.py build
  File "setup.py", line 25
    tests_require      = tests_require,
    ^
SyntaxError: keyword argument repeated

"""Setup script for the 'xdis' distribution."""

from __pkginfo__ import \
    author,           author_email,       \
    license,          long_description,   classifiers,               \
    modname,          py_modules,         tests_require,            \
    scripts,          short_desc,         tests_require,             \
    VERSION,          web,                zip_safe

from setuptools import setup, find_packages
setup(
       author             = author,
       author_email       = author_email,
       classifiers        = classifiers,
       description        = short_desc,
       license            = license,
       long_description   = long_description,
       name               = modname,
       packages           = find_packages(),
       py_modules         = py_modules,
       tests_require     = setup_requires,
       scripts            = scripts,
       tests_require      = tests_require,
       url                = web,
       version            = VERSION,
       zip_safe           = zip_safe)

**Comment by rocky** [comment]
I just downloaded the 3.3.0 tarball and I'm not seeing `tests_require` repeated.

**Comment by dol-sen** [comment]
Now this is truly strange...  I checked the tarball with archive-manager, opend setup.py and it is correct.
Yet our package manager repeatedly unpacks it with those errors...

It may be a compatibility issue between teh commands you made it with and the command being used by the package manager.

What command do you use to create the tarball?  setup.py sdist?
I'll check it out more in the morning

**Comment by rocky** [comment]
Yep, setup sdist. This kind of stuff has happened before on your end. Thing thing that gets me is how you often come across as so confident the problem lies elsewhere than your own code.
