### ISSUE TITLE
Tests fail with python-3.5.3, KeyError: b'\x17\r\r\n'

### ISSUE THREAD

**Issue by dol-sen** [rocky/python-xdis#34]
Seems python-3.5.3 has an unknown magic number, not yet listed in magics.py versions.

**Comment by dol-sen** [comment]
int2magic(3350): '3.5',       # 3.5.0, 3.5.1, 3.5.2
+    int2magic(3351): '3.5.3',     # 3.5.3
     int2magic(3361): '3.6.0a1',   # 3.6.0a1
     int2magic(3370): '3.6.0a1+1', # 3.6.0a?

Fixes it so far with 3.2.4 version

**Comment by rocky** [comment]
19be5e9 fixes. 

This will happen from time to time. Cool would be to submit a pull request

**Comment by dol-sen** [comment]
I would have submitted the change/patch I did to 3.2.4 as a PR, but The others around it had other assignments like the very next one '3.6.0a1'
And this isn't enough of a patch that I would want to credit for ;)
I thought it was better to just let you do it the way that fits your code best :)

Thank you
