### ISSUE TITLE
Possible wrong magin number for python 2.4a0

### ISSUE THREAD

**Issue by wizzycom** [rocky/python-xdis#69]
Hello,

First of all, that you for your effort on this. It is really a great tool!

It seems that magic number for python 2.4a0 is possibly declared wrong. 

add_magic_from_int(62041, "2.4a0")

Had to decompile some .pyc files of that version and I had some issues which were resovled by changing to 

add_magic_from_int(620**3**1, "2.4a0") 

And it works perfectly.

**Comment by rocky** [comment]
This is something that is easly checked. https://github.com/python/cpython/blob/ef82d2fdfe1aba18e29abbd59b22d19d490e9fca/Python/import.c#L52 listes 62041 as the final magic number fo "2.4a0". 

However in https://github.com/python/cpython/commit/ef82d2fdfe1 you'see that it had been 62031. 

> First of all, that you for your effort on this. It is really a great tool!

Sure, but open source is only as good as people willing to work on it. Feel free to work on something that might handle this. Perhaps an option on or parameter to override or add to the magic number?

**Comment by rocky** [comment]
See #70

**Comment by wizzycom** [comment]
My knowledge in python is limited. Elementary I might say. As an open source enthusiast, I agree that open source is only as good as people willing to work on it but there are always limits to what some people can do. Anyway, the only thing sure is that I will learn something new. I will update with my findings

Thank you!

**Comment by rocky** [comment]
> but there are always limits to what some people can do

While there is truth to this, it is also, well, _limiting_.   No one is born understanding how to do cross-disassembly and if you were task me as a kid would I be doing this, I would have looked at you dumbfounded if not said "absolutely not". 

There are other ways to contribute to - use your imagination. But failing that, then consider sponsoring the project and/or people doing this.
