### ISSUE TITLE
Unknown magic number: 62215

### ISSUE THREAD

**Issue by Zenexer** [rocky/python-xdis#7]
Dropbox seems to be using a magic number that isn't documented anywhere, as far as I can tell.  It's likely that they've modified the interpreter. 

```
/Applications/Dropbox.app/Contents/MacOS/python -V                                                                  :(
Python 2.7.11
```

When attempting to open one of Dropbox's pyo files with vanilla Python 2.7.12, I get:

```
python2.7 site.pyo
RuntimeError: Bad magic number in .pyc file
```

Obviously, there's no expectation for proprietary modifications to be supported, but if it's something as simple as adding the magic number, [I'm not the only one who would appreciate it](https://github.com/rocky/python-uncompyle6/issues/36).  This is particularly relevant given all the recent [commotion surrounding Dropbox's unusual security practices on macOS](https://news.ycombinator.com/item?id=12464730); many questions could be answered if the pyo files could be decompiled.

**Comment by rocky** [comment]
>  if it's something as simple as adding the magic number,

It isn't. Reread the thread in the link you cite.  Someone has to do the work for to get the information needed to address this. How about you?

**Comment by Zenexer** [comment]
@rocky Sure.  What do I need to do?  I'm playing around with it now, but not having much luck getting any info out of it.  Pretty sure they've mucked it up a bit.

**Comment by rocky** [comment]
My understanding is that they've added additional unmarshal code(s). Figure out what they are and what they do. 

See https://github.com/rocky/python-xdis/blob/master/xdis/unmarshal.py#L208 for how xdis handles unmarshaling codes. 

It is not unlikely that the additional codes might include things like decrypt bytecode or execute assembly code. If it is the latter, then you're going to need more than uncompyle6 to to get the full details. I'm assuming dropbox engineers are not stupid and did this for proprietary reasons. encryption methods _do_ exist that are virtually unbreakable. 

For understanding what the bytecode does, you'll probably have to step through the dropbox code in a debugger like gdb. Good luck!

**Comment by rocky** [comment]
I can add however 62215 in the magics file to note that it is a proprietary dropbox magic number.

**Comment by Zenexer** [comment]
I'll poke around in gdb and see what I can come up with.  I'm not too familiar with Python internals, though, so I might not get very far.

**Comment by rocky** [comment]
Just finding out what the additional codes are in the xdis unmashal.py routine will move this a little further in terms of documenting what's going on. Again, although we might not be able to deparse, at least more clarity can be given about what's going on.

**Comment by Zenexer** [comment]
Once I was sure it was encrypted, I started googling around and found this: https://github.com/rumpeltux/dropboxdec  Haven't looked at it yet, but might prove useful.

**Comment by Zenexer** [comment]
From https://itooktheredpill.irgendwo.org/2012/dropbox-decrypt/:

> The decryption also only works for the 1.1.45 version of dropbox. In the 1.2 branch the simple RNG was exchanged to the Mersenne Twister, so the decryption program would need to be adjusted accordingly.

> Yes this software is written explicitly for Dropbox 1.1.45, so it totally won’t work with newer versions. I only know that the RNG was exchanged in the 1.2 version, but don’t know if any other modifications were made.

> Have you tried this approach, perhaps:
Replace one of the .so files, that come inside the tarball (such as zlib.so) with your own
That version would — for each file — call into the PyMarshal_ReadObjectFromFile() — resolving that symbol from inside the executable itself. The returned object can then be dumped into a (separate) file and your patch function can be called to fix the op-codes.
This method has the potential of being future-proof — even if Dropbox decide to change the obfuscation method once again, the hack is likely to continue working.

@rumpeltux, would you be able to lend a hand?

**Comment by rocky** [comment]
@Zenexer @rumpeltux : I've now updated the magics for the dropbox versions of Python 2.5 and 2.7 and gave reference to https://itooktheredpill.irgendwo.org/2012/dropbox-decrypt/ . If there are additonal dropbox magics, e.g. let me know or add a pull request. 

As for automating the decoding in 2.5, I'll leave that for others.

**Comment by rocky** [comment]
Change that. I've done it for Python 2.7. For 3.x someone else can do. Ditto for other decryptions.
