### ISSUE TITLE
keyerror x(

### ISSUE THREAD

**Issue by venaxyt** [rocky/python-xdis#78]
it was working greatly on 3.9.5 after I edited python xdis scanners 37 & 37 and base 37 but now it make me another error since i upgraded on 3.9.6 KeyError: '3.9.6' on module xdis so i tried to add in python versions in xdis module but it does not works. Thanks for any help

**Comment by venaxyt** [comment]
note : i tried e v e r y t h i n g  editing much file parts of xdis...

**Comment by rocky** [comment]
https://github.com/rocky/python-xdis/commit/af2d74158e268b6fdfcca3f275b1f7b05b3a8eb6 adds detection for 3.9.6 so just use the current github sources.

**Comment by venaxyt** [comment]
thanks bro i'm gonna try this

**Comment by venaxyt** [comment]
File "C:\Users\terys\AppData\Local\Programs\Python\Python39\lib\site-packages\xdis\load.py", line 167, in load_module
    return load_module_from_file_object(
  File "C:\Users\terys\AppData\Local\Programs\Python\Python39\lib\site-packages\xdis\load.py", line 310, in load_module_from_file_object
    raise ImportError(
ImportError: Ill-formed bytecode file C:\Users\terys\AppData\Local\Temp\tmp1svbx51_.pyc
<class 'AssertionError'>; co_code should be one of the types (<class 'str'>, <class 'bytes'>, <class 'list'>, <class 'tuple'>); is type <class 'NoneType'>


x(
