### ISSUE TITLE
Need more investigations: `xdis.unmarshal._VersionIndependentUnmarshaller` method `t_object_reference`

### ISSUE THREAD

**Issue by rakovskij-stanislav** [rocky/python-xdis#89]
Method `t_object_reference` of `xdis.unmarshal._VersionIndependentUnmarshaller` probably wants `internObjects[refnum-1]`, not `internObjects[refnum]`

Found this bug while unmarshalling py2exe bootstrap code object (it's safe despite it was got from malware sample, but anyway be careful).

code object in base64:
```
YwAAAAAAAAAAAAAAAAAAAAADAAAAQAAAAHMuAAAAZABkAWwAWgBkAGQBbAFaAWUAagKgA2UBagShAQQAZQFfBWUBXwZbAFsBZAFTACkC6QAAAABOKQfaAm9z2gNzeXPaBHBhdGjaB2Rpcm5hbWXaCmV4ZWN1dGFibGXaC2Jhc2VfcHJlZml42gZwcmVmaXipAHIJAAAAcgkAAAD6DDxib290c3RyYXAyPtoIPG1vZHVsZT4BAAAAcwQAAAAQABYA
```

![](https://user-images.githubusercontent.com/25303578/143689198-6b5cc652-19e4-463d-88ae-1997aebbd4ba.png)

On the screenshot:
`internObjects[refnum]` => `internObjects[9]` => Exception.

This code object got from normal-working file, this way the problem in `_VersionIndependentUnmarshaller`

The fix is to use `refnum-1`, but I want to make sure that this fix is proper.

**Comment by rocky** [comment]
To verify it is a bug. Start with python source code, byte compile the code. And then disassemble the code both with the native `dis` module and with xdis's disassembler from another Python version.

**Comment by rakovskij-stanislav** [comment]
I have no source code, but I have a possibility to load native code object and Code38 object. One sec...

**Comment by rocky** [comment]
> I have no source code, 

Then you don't have a reportable bug yet.

**Comment by rakovskij-stanislav** [comment]
https://github.com/py2exe/py2exe/blob/fdde3fa18fac86304f2e6d3279d3c487a88dabd1/py2exe/runtime.py#L607 - the line of adding this code object.

Bug was in my part of deserialization - I prepared the first byte (because Fast Unmarshaller of xdis did not do it - and refused to unmarshal.
```
obj_bytes = bytes([obj_bytes[0] & 0x7F]) + obj_bytes[1:]
```
Commented out this part - and xdis _VersionIndependentUnmarshaller started to work)
