### ISSUE TITLE
Use dispatch table in unmarshal? 

### ISSUE THREAD

**Issue by rocky** [rocky/python-xdis#9]
Should be faster than the `if` .. `elif'`s

**Comment by gsb-eng** [comment]
@rocky I've made some improvements for this in the new repo that I've started [here](https://github.com/gsb-eng/pydis/blob/master/pydis/unmarshal.py).

How to contact you? email? irc?

**Comment by rocky** [comment]
Information about this package in pypi will work.

**Comment by rocky** [comment]
This was done a while ago.
